server:
    port: 8080
    error:
        include-message: always
        include-binding-errors: always
        include-exception: true
        # include-stacktrace: always

logging:
    level:
        mywild: TRACE
        # org:
        #     springframework:
        #         security: TRACE

springdoc:
    swagger-ui:
        persist-authorization: true
        filter: true
        tags-sorter: alpha

mywild:
    app:
        version: @project.version@
    jwt:
        issuer: MyWild
        subject: WildEvents
        audience: ${JWT_AUDIENCE}
        access-token-duration: 60
        refresh-token-duration: 362
    key:
        private: ${PRIVATE_KEY}
        public: ${PUBLIC_KEY}
    cors: ${CORS}
    wildevents:
        page-size: 10
        max-activities-per-event: 5
        max-inat-results-per-activity: 20000

spring:
    main:
        lazy-initialization: true
    jmx:
        enabled: false
    config:
        import: optional:file:./.env[.properties]
    cloud:
        azure:
            cosmos:
                key: ${AZURE_COSMOS_KEY}
                endpoint: ${AZURE_COSMOS_ENDPOINT}
                database: ${AZURE_COSMOS_DATABASE}
