name: Build Spring Docker Image

on: workflow_dispatch
    # push:
    #     branches: [master]
    # pull_request:
    #     branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: 17
                  distribution: temurin
                  cache: maven

            - name: Build Spring App with Maven
              run: mvn -B clean package
    
            - name: Build Docker Image with Maven
              run: mvn spring-boot:build-image

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
                
            - name: Push Docker image
              uses: docker/build-push-action@v5
              with:
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/wildwatch:latest
